/*
 * This file is generated by jOOQ.
 */
package de.hft.licensing.db.enums;


import de.hft.licensing.db.Licensing;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum LicenseStatus implements EnumType {

    active("active"),

    suspended("suspended"),

    expired("expired");

    private final String literal;

    private LicenseStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return Licensing.LICENSING;
    }

    @Override
    public String getName() {
        return "license_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static LicenseStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(LicenseStatus.class, literal);
    }
}
