/*
 * This file is generated by jOOQ.
 */
package de.hft.licensing.db.tables.records;


import de.hft.licensing.db.enums.ApplicationStatus;
import de.hft.licensing.db.enums.LicenseType;
import de.hft.licensing.db.tables.Application;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApplicationRecord extends UpdatableRecordImpl<ApplicationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>licensing.application.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>licensing.application.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>licensing.application.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>licensing.application.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>licensing.application.license_type</code>.
     */
    public void setLicenseType(LicenseType value) {
        set(2, value);
    }

    /**
     * Getter for <code>licensing.application.license_type</code>.
     */
    public LicenseType getLicenseType() {
        return (LicenseType) get(2);
    }

    /**
     * Setter for <code>licensing.application.cadastral_reference</code>.
     */
    public void setCadastralReference(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>licensing.application.cadastral_reference</code>.
     */
    public String getCadastralReference() {
        return (String) get(3);
    }

    /**
     * Setter for <code>licensing.application.applied_at</code>.
     */
    public void setAppliedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>licensing.application.applied_at</code>.
     */
    public LocalDateTime getAppliedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>licensing.application.changed_at</code>.
     */
    public void setChangedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>licensing.application.changed_at</code>.
     */
    public LocalDateTime getChangedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>licensing.application.application_status</code>.
     */
    public void setApplicationStatus(ApplicationStatus value) {
        set(6, value);
    }

    /**
     * Getter for <code>licensing.application.application_status</code>.
     */
    public ApplicationStatus getApplicationStatus() {
        return (ApplicationStatus) get(6);
    }

    /**
     * Setter for <code>licensing.application.remarks</code>.
     */
    public void setRemarks(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>licensing.application.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplicationRecord
     */
    public ApplicationRecord() {
        super(Application.APPLICATION);
    }

    /**
     * Create a detached, initialised ApplicationRecord
     */
    public ApplicationRecord(Integer id, String userId, LicenseType licenseType, String cadastralReference, LocalDateTime appliedAt, LocalDateTime changedAt, ApplicationStatus applicationStatus, String remarks) {
        super(Application.APPLICATION);

        setId(id);
        setUserId(userId);
        setLicenseType(licenseType);
        setCadastralReference(cadastralReference);
        setAppliedAt(appliedAt);
        setChangedAt(changedAt);
        setApplicationStatus(applicationStatus);
        setRemarks(remarks);
        resetChangedOnNotNull();
    }
}
