/*
 * This file is generated by jOOQ.
 */
package de.hft.licensing.db;


import de.hft.licensing.db.tables.Application;
import de.hft.licensing.db.tables.ApplicationPayment;
import de.hft.licensing.db.tables.License;
import de.hft.licensing.db.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Licensing extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>licensing</code>
     */
    public static final Licensing LICENSING = new Licensing();

    /**
     * The table <code>licensing.application</code>.
     */
    public final Application APPLICATION = Application.APPLICATION;

    /**
     * The table <code>licensing.application_payment</code>.
     */
    public final ApplicationPayment APPLICATION_PAYMENT = ApplicationPayment.APPLICATION_PAYMENT;

    /**
     * The table <code>licensing.license</code>.
     */
    public final License LICENSE = License.LICENSE;

    /**
     * The table <code>licensing.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Licensing() {
        super("licensing", null);
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.APPLICATION_ID_SEQ,
            Sequences.APPLICATION_PAYMENT_ID_SEQ,
            Sequences.LICENSE_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Application.APPLICATION,
            ApplicationPayment.APPLICATION_PAYMENT,
            License.LICENSE,
            User.USER
        );
    }
}
