/*
 * This file is generated by jOOQ.
 */
package de.hft.licensing.db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in licensing.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>licensing.application_id_seq</code>
     */
    public static final Sequence<Long> APPLICATION_ID_SEQ = Internal.createSequence("application_id_seq", Licensing.LICENSING, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>licensing.application_payment_id_seq</code>
     */
    public static final Sequence<Long> APPLICATION_PAYMENT_ID_SEQ = Internal.createSequence("application_payment_id_seq", Licensing.LICENSING, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>licensing.license_id_seq</code>
     */
    public static final Sequence<Long> LICENSE_ID_SEQ = Internal.createSequence("license_id_seq", Licensing.LICENSING, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
