events {}

http {

  upstream backend_upstream {
    least_conn;
    server backend:8080;
  }

  upstream document_validator {
    server mock-document-validator:8080;
  }

  upstream keycloak {
    server keycloak:8080;
  }

  server {
    listen 80;

    # Backend API (Load Balanced)
    location / {
      proxy_pass http://backend_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;
    }

    # Mock Document Validator
    # Routed via backend API
    location /process-document/ {
      rewrite ^/process-document/?(.*)$ /$1 break;
      proxy_pass http://document_validator;
    }

    # Keycloak (optional)
    location /auth/ {
      proxy_pass http://keycloak;
    }
  }
}