# DB CREDENTIALS - DO NOT CHANGE!!!
services:
  postgres:
    image: postgres:18.0
    environment:
    - POSTGRES_DB=government
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=P4ssword!
    ports:
    - "5433:5432"
    volumes:
      - kc_db:/var/lib/postgresql

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    command:
      - start-dev
      - --import-realm
      - --features=scripts
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts
      KC_SCRIPTS_UPLOAD_ENABLED: "true"
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import

  mock-bank:
    build:
      context: ../license-application-mock-bank
      dockerfile: Dockerfile
    container_name: mock-bank
    ports:
      - "8082:8080"
    restart: unless-stopped

  mock-document-validator:
    build:
      context: ../license-application-mock-validator
      dockerfile: Dockerfile
    container_name: mock-document-validator
    ports:
      - "8083:8080"
    restart: unless-stopped

volumes:
  kc_db:
# THE ACTUAL BACKENDS
  backend1:
    image: license-application-service-backend  # Or build context if you build locally
    container_name: backend-instance-1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres:5432/government
      - DB_USER=postgres
      - DB_PASSWORD=P4ssword!
      - KEYCLOAK_AUTH-SERVER-URL=http://keycloak:8080
    depends_on:
      - postgres
      - keycloak
    networks:
      - app-network

  backend2:
    image: license-application-service-backend # Same image!
    container_name: backend-instance-2
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres:5432/government
      - DB_USER=postgres
      - DB_PASSWORD=P4ssword!
      - KEYCLOAK_AUTH-SERVER-URL=http://keycloak:8080
    depends_on:
      - postgres
      - keycloak
    networks:
      - app-network

  # THE LOAD BALANCER
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge