spring:
  application:
    name: licensing
  liquibase:
    change-log: db/master-changelog.xml
    default-schema: licensing
    liquibase-schema: public
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/license-realm
  docker:
    compose:
      lifecycle-management: start-only
      file: license-application-service/docker-compose.yml
  jooq:
    sql-dialect: postgres

  mail:
    host: smtp.gmail.com
    port: 587
    username: projectlegerski@gmail.com
    password: earm afra dnfn vnpp
    debug: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com
  config:
    import:
      - optional:file:license-application-service/.env # for local builds
      - optional:file:/app/.env # for docker containers

logging.level.org.jooq.Constants: off

springdoc:
  swagger-ui:
    operations-sorter: alpha
    oauth:
      client-id: backend-api
      client-secret: "CLIENT_SECRET_PLACEHOLDER"
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR

keycloak:
  url: http://localhost:8081
  realm: license-realm
  client-id: backend-api
  client-secret: "CLIENT_SECRET_PLACEHOLDER"

mockbank:
  base-url: http://localhost:8082