spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/government}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
  application:
    name: licensing
  liquibase:
    change-log: db/master-changelog.xml
    default-schema: licensing

  docker:
    compose:
      lifecycle-management: start-only
      file: license-application-service/docker-compose.yml
  jooq:
    sql-dialect: postgres

springdoc:
  swagger-ui:
    operations-sorter: alpha

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
