spring:
  application:
    name: licensing
  liquibase:
    change-log: db/master-changelog.xml
    default-schema: licensing
    liquibase-schema: public
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/license-realm
  docker:
    compose:
      lifecycle-management: start-only
      file: license-application-service/docker-compose.yml
  jooq:
    sql-dialect: postgres
logging.level.org.jooq.Constants: off

springdoc:
  swagger-ui:
    operations-sorter: alpha

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR

keycloak:
  url: http://localhost:8081
  realm: license-realm
  client-id: backend-api
  client-secret: SKhzmEzB3STLmu8Q79yAdStIl2KCjFIW
