/*
 * This file is generated by jOOQ.
 */
package de.hft.licensing.db.tables;


import de.hft.licensing.db.Keys;
import de.hft.licensing.db.Licensing;
import de.hft.licensing.db.enums.ApplicationStatus;
import de.hft.licensing.db.enums.LicenseType;
import de.hft.licensing.db.tables.ApplicationPayment.ApplicationPaymentPath;
import de.hft.licensing.db.tables.License.LicensePath;
import de.hft.licensing.db.tables.User.UserPath;
import de.hft.licensing.db.tables.records.ApplicationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Application extends TableImpl<ApplicationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>licensing.application</code>
     */
    public static final Application APPLICATION = new Application();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ApplicationRecord> getRecordType() {
        return ApplicationRecord.class;
    }

    /**
     * The column <code>licensing.application.id</code>.
     */
    public final TableField<ApplicationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>licensing.application.user_id</code>.
     */
    public final TableField<ApplicationRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * The column <code>licensing.application.license_type</code>.
     */
    public final TableField<ApplicationRecord, LicenseType> LICENSE_TYPE = createField(DSL.name("license_type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(LicenseType.class), this, "");

    /**
     * The column <code>licensing.application.cadastral_reference</code>.
     */
    public final TableField<ApplicationRecord, String> CADASTRAL_REFERENCE = createField(DSL.name("cadastral_reference"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>licensing.application.applied_at</code>.
     */
    public final TableField<ApplicationRecord, LocalDateTime> APPLIED_AT = createField(DSL.name("applied_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>licensing.application.changed_at</code>.
     */
    public final TableField<ApplicationRecord, LocalDateTime> CHANGED_AT = createField(DSL.name("changed_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>licensing.application.application_status</code>.
     */
    public final TableField<ApplicationRecord, ApplicationStatus> APPLICATION_STATUS = createField(DSL.name("application_status"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(ApplicationStatus.class), this, "");

    /**
     * The column <code>licensing.application.remarks</code>.
     */
    public final TableField<ApplicationRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.CLOB, this, "");

    private Application(Name alias, Table<ApplicationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Application(Name alias, Table<ApplicationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>licensing.application</code> table reference
     */
    public Application(String alias) {
        this(DSL.name(alias), APPLICATION);
    }

    /**
     * Create an aliased <code>licensing.application</code> table reference
     */
    public Application(Name alias) {
        this(alias, APPLICATION);
    }

    /**
     * Create a <code>licensing.application</code> table reference
     */
    public Application() {
        this(DSL.name("application"), null);
    }

    public <O extends Record> Application(Table<O> path, ForeignKey<O, ApplicationRecord> childPath, InverseForeignKey<O, ApplicationRecord> parentPath) {
        super(path, childPath, parentPath, APPLICATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ApplicationPath extends Application implements Path<ApplicationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ApplicationPath(Table<O> path, ForeignKey<O, ApplicationRecord> childPath, InverseForeignKey<O, ApplicationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ApplicationPath(Name alias, Table<ApplicationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ApplicationPath as(String alias) {
            return new ApplicationPath(DSL.name(alias), this);
        }

        @Override
        public ApplicationPath as(Name alias) {
            return new ApplicationPath(alias, this);
        }

        @Override
        public ApplicationPath as(Table<?> alias) {
            return new ApplicationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Licensing.LICENSING;
    }

    @Override
    public Identity<ApplicationRecord, Integer> getIdentity() {
        return (Identity<ApplicationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ApplicationRecord> getPrimaryKey() {
        return Keys.APPLICATION_PKEY;
    }

    @Override
    public List<ForeignKey<ApplicationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.APPLICATION__APPLICATION_USER_ID_FKEY);
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>licensing.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.APPLICATION__APPLICATION_USER_ID_FKEY, null);

        return _user;
    }

    private transient ApplicationPaymentPath _applicationPayment;

    /**
     * Get the implicit to-many join path to the
     * <code>licensing.application_payment</code> table
     */
    public ApplicationPaymentPath applicationPayment() {
        if (_applicationPayment == null)
            _applicationPayment = new ApplicationPaymentPath(this, null, Keys.APPLICATION_PAYMENT__APPLICATION_PAYMENT_APPLICATION_ID_FKEY.getInverseKey());

        return _applicationPayment;
    }

    private transient LicensePath _license;

    /**
     * Get the implicit to-many join path to the <code>licensing.license</code>
     * table
     */
    public LicensePath license() {
        if (_license == null)
            _license = new LicensePath(this, null, Keys.LICENSE__LICENSE_APPLICATION_ID_FKEY.getInverseKey());

        return _license;
    }

    @Override
    public Application as(String alias) {
        return new Application(DSL.name(alias), this);
    }

    @Override
    public Application as(Name alias) {
        return new Application(alias, this);
    }

    @Override
    public Application as(Table<?> alias) {
        return new Application(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Application rename(String name) {
        return new Application(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Application rename(Name name) {
        return new Application(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Application rename(Table<?> name) {
        return new Application(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Application where(Condition condition) {
        return new Application(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Application where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Application where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Application where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Application where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Application where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Application where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Application where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Application whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Application whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
