package de.hft.licensing.utils;

import de.hft.licensing.db.enums.ApplicationStatus;
import de.hft.licensing.db.enums.LicenseStatus;
import de.hft.licensing.db.enums.LicenseType;
import de.hft.licensing.db.enums.PaymentStatus;
import de.hft.licensing.model.ApplicationStatusApiEnum;
import de.hft.licensing.model.LicenseStatusApiEnum;
import de.hft.licensing.model.LicenseTypeApiEnum;
import de.hft.licensing.model.PaymentStatusApiEnum;

public class EnumMapperUtil {

    /**
     * Returns the corresponding enum constant from the complementary enum type.
     * <p>
     * In this project, two separate enum types exist for each conceptual class:
     * one generated for the API resources (e.g., {@code ApplicationStatusApiEnum})
     * and one generated by jOOQ for the database resources (e.g., {@code ApplicationStatus}).
     * This method provides a generic way to map between these two representations.
     * </p>
     *
     * <p>For example:</p>
     * <ul>
     *   <li>If the input is an API enum such as {@code ApplicationStatusApiEnum},
     *       the method returns the corresponding jOOQ enum {@code ApplicationStatus}.</li>
     *   <li>If the input is a jOOQ enum such as {@code ApplicationStatus},
     *       the method returns the corresponding API enum {@code ApplicationStatusApiEnum}.</li>
     * </ul>
     *
     * <p>The mapping is determined based on the enum value or literal using
     * the appropriate lookup or conversion methods defined in the enum classes.</p>
     *
     * @param <T> the type of the input enum (either API or jOOQ enum)
     * @param <R> the type of the corresponding enum to be returned
     * @param enumValue the enum constant for which to find the corresponding counterpart;
     *                  may be {@code null}
     * @return the corresponding enum constant from the complementary enum type,
     *         or {@code null} if the input is {@code null} or no matching mapping exists
     *
     * @implNote
     * This method relies on a {@code switch} expression to handle the supported enum pairs.
     * If new enum types are introduced in the future, they must be added to the switch.
     */

    @SuppressWarnings("unchecked")
    public static <T extends Enum<?>, R extends Enum<?>> R getPendantFromEnum(T enumValue) {
        if (enumValue == null) return null;
        return (R) switch (enumValue) {
            case ApplicationStatusApiEnum e -> ApplicationStatus.lookupLiteral(e.getValue().toLowerCase());
            case ApplicationStatus e -> ApplicationStatusApiEnum.fromValue(e.getLiteral().toUpperCase());
            case LicenseTypeApiEnum e -> LicenseType.lookupLiteral(e.getValue().toLowerCase());
            case LicenseType e -> LicenseTypeApiEnum.fromValue(e.getLiteral().toUpperCase());
            case LicenseStatusApiEnum e -> LicenseStatus.lookupLiteral(e.getValue().toLowerCase());
            case LicenseStatus e -> LicenseStatusApiEnum.fromValue(e.getLiteral().toUpperCase());
            case PaymentStatusApiEnum e -> PaymentStatus.lookupLiteral(e.getValue().toLowerCase());
            case PaymentStatus e -> PaymentStatusApiEnum.fromValue(e.getLiteral().toUpperCase());
            default -> null;
        };
    }

}
