events {
    worker_connections 1024;
}

http {
    upstream backend_servers {
        # Docker DNS does the load balancing
        server backend:8080;
    }

    server {
        listen 80;
        server_name localhost;
        # Reverse proxy for document validation service
        location /process-document {
            proxy_pass http://localhost:8083/process-document;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://backend_servers;

            # Proxy headers
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Timeouts
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
    }
}
